[workspace]
members = ["rusistor", "tusistor", "tusistor-core", "tusistor-web" ]
resolver = "2"

[workspace.package]
authors = ["dawe <dawedawe@posteo.de>"]
license = "MIT"
edition = "2024"
repository = "https://github.com/dawedawe/tusistor"

