[package]
name = "rusistor"
version = "0.2.1"
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
description = "A library to calculate color codes and specs of electrical resistors."

[dependencies]
